# Generated by Django 4.0.4 on 2022-05-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_alter_role_description_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.level'),
        ),
    ]
