# Generated by Django 4.0.4 on 2022-05-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0004_alter_structure_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
