# Generated by Django 4.0.4 on 2022-05-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0006_alter_structure_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='structure_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.level'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
