# Generated by Django 4.0.4 on 2022-05-29 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0007_structure_structure_level_alter_structure_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
